### ISSUE TITLE
Add APP_ env vars into backend/docs

### ISSUE THREAD

**Issue by sadikkuzu-boun** [sadikkuzu-boun/facebook-marketing#8]
https://github.com/sadikkuzu-boun/facebook-marketing/blob/a5a73ab389b434a8217cc66af43f3d8ff3f73890/backend/.env.sample#L1-L3

Add APP_ environment variables into [backend/docs](https://github.com/sadikkuzu-boun/facebook-marketing/blob/main/backend/docs/README.md)

**Comment by sadikkuzu** [comment]
Live by https://github.com/sadikkuzu-boun/facebook-marketing/commit/b7f767d7d337c25c441cfdb13a9a98d2c3b0b0f3
